inaka/elvis

src/elvis_style.erl
Elvis reported erroneously that there is a missing space in https://github.com/for-GET/katt/blob/38a71342aa33ce23f01efce8557a2c71b61e37f0/src/katt_util.erl#L329
After investigating, it seems that elvis (or actually katana) is unable to find the node. My guess is that the guard is too naïve https://github.com/inaka/elvis/blob/2ac9651e45de240e3531943d22d1ea5de433dbd5/src/elvis_code.erl#L75 but I'm not going to investigate that now.
Regardless of the core reason, if elvis find a possible error, but cannot verify that it is indeed an error (in this case find the node), it's better to keep quiet (no false positives).
=> Bypass operator_spaces when unable to find node type

src/elvis_style.erl
Reverts inaka/elvis#189
> I'm reverting this PR because it breaks [this test](https://github.com/inaka/elvis/blob/master/test/style_SUITE.erl#L122).
> The line (in the code) that goes undetected is this one:
> ```erlang
>   _Unless = [we, consider]++ [operands, as, well],
> ```
> 
> We must find a way to handle both @andreineculau's scenario *and also* the currently tested one.
=> Revert "Bypass operator_spaces when unable to find node type"

CHANGELOG.md, config/elvis-test.config, config/elvis.config, config/old/elvis-test-rule-config-list.config, config/test.config, src/elvis_project.erl, test/examples/Makefile.fail, test/examples/rebar.config.fail, test/project_SUITE.erl
The rule should allow specifying which protocols (https, ssh, or git) should be allowed in the rebar.config and Makefile files for specifying dependencies.
See [this](https://github.com/inaka/erlang_guidelines/issues/27)
=> Rule to enforce dependency url fetch protocol

Makefile, src/elvis_code.erl, src/elvis_style.erl, src/elvis_utils.erl, test/elvis_SUITE.erl, test/examples/fail_line_length.erl, test/examples/fail_operator_spaces.erl, test/style_SUITE.erl
=> [Closes #181] Operator spaces bug

README.md, config/elvis.config, config/test.config, src/elvis_style.erl, test/examples/fail_no_trailing_whitespace.erl, test/style_SUITE.erl
This rule is based on the no_tabs rule, but checks for trailing
whitespace instead. The 'info' field of the elvis items returned contain
the position, length, and the contents of the matched trailing
whitespace. It could be useful for debugging.
=> Add rule checking for trailing whitespace

src/elvis_style.erl
=> [#28] Updated zipper functions after renaming edit_all to fmap

README.md, src/elvis_webhook.erl
[Fix #216] take elvis.config from current branch
=> [Fix #216] take elvis.config from current branch

README.md, config/test.config, src/elvis.erl, src/elvis_utils.erl, test/elvis_SUITE.erl
[Fix #209] add output-format option to show result without colors
=> [Fix #209] add output-format option to show result without colors

elvis.config, src/elvis_style.erl, test/examples/fail_no_spaces.erl, test/style_SUITE.erl
[Close #178] add no spaces rule
=> WIP [Close #178] add no spaces rule

Makefile, test/examples/fail_dont_repeat_yourself.erl, test/examples/pass_dont_repeat_yourself.erl
=> [Closes #239] Updated katana dep to 0.2.7, add spec with fun((...) -> ok)

Makefile, rebar.config, src/elvis_project.erl, test/examples/rebar.config.fail
Trying to use apns4erl I'm getting this problem:
```
* katana (https://github.com/inaka/erlang-katana.git)
the dependency katana in deps/apns/rebar.config is overriding a child dependency:
> In deps/apns/rebar.config:
{:katana, ~r/.*/, [git: "https://github.com/inaka/erlang-katana.git", tag: "0.2.0"]}
> In deps/elvis/rebar.config:
{:katana, ~r/.*/, [git: "git://github.com/inaka/erlang-katana", ref: "0.2.0"]}
```
So I'm trying to normalize it as `https` in the all sub-dependencies of apns4erl since https is the protocol recommended by github on remotes.
=> Use https instead of git remotes

src/elvis.erl, src/elvis_utils.erl
* fix target type elvis:rock_this
* change spec in elvis_utils:erlang_halt to no_return()
=> Fix typo in specs

Makefile, src/elvis_code.erl, src/elvis_style.erl, test/examples/fail_operator_spaces.erl, test/xref_SUITE.erl
=> [Closes #236] Operator space false positive

CHANGELOG.md, src/elvis.app.src, src/elvis_config.erl, test/elvis_SUITE.erl
=> [Closes #271] Release 0.2.6-alpha1

src/elvis_project.erl, test/examples/rebar.config.fail, test/project_SUITE.erl
Elvis fails on a rebar.config file which uses Rebar3 style deps with the following error.
```
Error: 'function_clause' while applying rule 'protocol_for_deps_rebar'.
Loading files...
Applying rules...
```
This is the style which it fails on.
```
{deps, [
{poolboy, {git, "https://github.com/devinus/poolboy.git", {tag, "1.5.1"}}},
{gproc,   {git, "https://github.com/uwiger/gproc.git", {branch, "master"}}}
]
}.
```
=> Support for Rebar3 style deps

Makefile
#258 
Also removed unnecessary dependency `aleppo` and updated test dep `meck` so that it doesn't run `doc` and `test` targets on `make all`.
=> [Closes #258] Updated katana dep which handles changes in OTP 18.0

src/elvis_config.erl
In `elvis_config` you'll find
```erlang
-type config() :: map().
```
when in fact it should be
```erlang
-type config() :: [map()].
```
=> Wrong config spec

src/elvis_project.erl, test/examples/rebar3.config.success, test/project_SUITE.erl
Fix the handling of hex based dependencies so they are ignored instead of crashing the test.
=> Rebar3 fix

Makefile, rebar.config
the `variable_naming_convention` rule complains incorrectly about MACRO names
=> variable_naming_convention and MACROs

src/elvis.erl, src/elvis_git.erl, test/git_SUITE.erl
Expand elvis with an option to run Elvis on all changes since a particular branch or sha. I would like to be able to run elvis on a Jenkins run and would like to get the entire diff of the branch rather than as a commit-hook or webhook (which doesn't work for in-house hosted Bitbucket server)
Example:
`elvis git-branch origin/master`
`elvis git-branch a441b15`
Fixes: #420
=> Add option for running Elvis on all changes since branch or commit

src/elvis.erl
This switch will force Elvis to keep rocking even when it encounters an error. It applies to a case when a list of files to rock is provided. Default behaviour causes the script to stop on first faulty module.
It's useful for rocking group of modules selected with regexp. First of all, it allows to learn an overview of errors in all modules. Secondly, now it's possible to ignore some errors that are tricky to resolve (like god modules) and continue to remaining mods.
=> Add --keep-rocking switch

src/elvis.erl
Now with the corresponding [elvis_core PR](https://github.com/inaka/elvis_core/pull/88), it'll behave as follows:
```interactive
$ elvis --output-format plain --verbose rock
Loading files...
Loading src/elvis.erl
Loading src/elvis_git.erl
Loading src/elvis_webhook.erl
Loading test/elvis_SUITE.erl
Loading test/elvis_meta_SUITE.erl
Loading test/git_SUITE.erl
Loading test/xref_SUITE.erl
Applying rules...
- no_tabs
- Line 18 has a tab at column 0.
Loading files...
Applying rules...
Loading files...
Loading rebar.config
Applying rules...
Loading files...
Loading elvis.config
Applying rules...
$
```
vs
```interactive
$ elvis --output-format plain rock
- no_tabs
- Line 18 has a tab at column 0.
$
```
I've also thought that it might make sense to expose the existing `no_output` app env setting, …
=> Add `--verbose` flag, setting verbose app env option

README.md
I realized that when I introduced the git-branch option a while ago, I didn't add it to the README. The only way it's documented as of now is if you run elvis --commands. I believe this option is beneficial for quite some projects so it'd be nice to have it slightly more prominent in the README.
=> Add git-branch option for elvis escript to readme

src/elvis.app.src, src/elvis.erl
This change allows to use Elvis without any configuration file.
=> Add non-empty default configuration

rebar.config
Warning is `Warning: erlang:get_stacktrace/0: deprecated; use the new try/catch syntax for retrieving the stack backtrace`.
=> Prevent a minor warning (and prepare for the future)

ci, rebar.config, test/examples/fail_dont_repeat_yourself.erl, test/examples/user_defined_rules.erl
Though `eunit` tests aren't present, it's still possible to prevent issues for them with these minor changes; otherwise they show up as errors and this might confuse the developer.
I took the time to add `elvis` to CI, for increased goodness.
=> Prevent eunit issues + Rock with Elvis

rebar.config
There's no real value in the documentation of the API since this is not a consumable dependency, but more like a local service.
=> Hide API Reference from hexdocs.pm

README.md
#587 went by so fast I almost didn't have time to self-review 😄 
Now that it's rendered I think a minor adjustment is in order.
As before, I used `[no ci]` in the commit message to bypass CI.
=> Tweak the webhook section divisions

.github/workflows/ci.yml, .gitignore, README.md, priv/bash_completion/elvis, priv/zsh_completion/_elvis, rebar.config
Closes #590.
These can always be improved, but a first step's a first step.
If you release after this (I just need a Git tag, really) I'll add it to the `brew.sh` package.
=> Add shell completions for Bash and Zsh
