inaka/elvis

src/elvis_git.erl
test/git_SUITE.erl

Fix https://github.com/inaka/elvis/issues/193

Ensure that 'elvis git-hook' does not check deleted files

---

src/elvis_webhook.erl

…once inaka/erlang-github#19 is done

Fix elvis_webhook according to the new version of egithub_webhook

---

Makefile
config/elvis.config
src/elvis_code.erl
src/elvis_git.erl
src/elvis_style.erl
test/examples/fail_dont_repeat_yourself.erl
test/examples/pass_dont_repeat_yourself.erl
test/style_SUITE.erl

#28
Waiting for inaka/zipper#16 PR to be merged and the release `0.1.2` created.

WIP [#28] DRY rule

---

src/elvis_project.erl
test/project_SUITE.erl

[Close #199] improve protocol for deps

[Close #199] improve protocol for deps

---

test/style_SUITE.erl

Fix bad type

---

src/elvis.erl
test/elvis_SUITE.erl

[Close #174] add version option

[Close #174] add version option

---

config/elvis-test.config
config/elvis.config
config/old/elvis-test-rule-config-list.config
config/test.config
elvis.config
src/elvis_project.erl
test/project_SUITE.erl

[Close #238] change https protocol as default for deps rule

[Close #238] change https protocol as default for deps rule

---

src/elvis_git.erl

Added '\' to patch_line_type() function

---

CHANGELOG.md

Version bump 0.2.5-beta4

---

src/elvis_style.erl
test/examples/fail_max_module_length.erl
test/examples/fail_operator_spaces.erl
test/style_SUITE.erl

[Closes #152] Max module length rule

---

src/elvis.erl
src/elvis_config.erl
src/elvis_file.erl
src/elvis_webhook.erl
test/elvis.coverspec
test/elvis_SUITE.erl

[Closes #252] Incorrect matching of files

---

config/test.config
src/elvis_file.erl

[Closes #273] Add global option to re:replace call

---

.gitignore
Makefile
erlang.mk

There is no repository for `sync`: https://github.com/inaka/elvis/blob/master/Makefile#L6
Is it really a dependency?

Missing dependency repository

---

CHANGELOG.md
Makefile
src/elvis_shell.app.src

[Fix #328] update release 0.2.6

[Fix #328] update release 0.2.6

---

Makefile
rebar.config

[#335] Update elvis_core version to 0.2.7

---

CHANGELOG.md
src/elvis_shell.app.src

[Close #337] Update elvis_core version to 0.2.7

---

CHANGELOG.md
Makefile
src/elvis_shell.app.src

For both elvis_core and this repo

Version Bump to 0.2.10

---

rebar.config
rebar.lock
src/elvis_git.erl
src/elvis_webhook.erl
test/elvis_meta_SUITE.erl

[#424] updating dependencies

---

src/elvis.erl

[#419] link to correct version

---

CHANGELOG.md
src/elvis_shell.app.src

[#429] Bump Version to 0.3.1

---

CHANGELOG.md
src/elvis_shell.app.src

[#431] version bump to 0.3.2

---

.travis.yml
README.md
ci
rebar.config
test/elvis_SUITE.erl
test/git_SUITE.erl

[#456] Adding Travis

---

src/elvis.app.src

As per https://github.com/inaka/elvis/pull/521#discussion_r485538042.

Simplify defaults in .app.src

---

README.md

Remove unreachable stuff

---

README.md

For the stuff we're [discussing here](https://github.com/inaka/elvis/issues/553).

Wiki-provoked changes
